//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Proyectoes = new HashSet<Proyecto>();
        }

        [Display(Name = "Cédula")]
        public string cedulaPK
        {
            get; set;
        }
        [Display(Name = "Nombre")]
        public string nombreP
        {
            get; set;
        }
        [Display(Name = "Primer Apellido")]
        public string apellido1
        {
            get; set;
        }
        [Display(Name = "Segundo Apellido")]
        public string apellido2
        {
            get; set;
        }
        [Display(Name = "Teléfono")]
        public string telefono
        {
            get; set;
        }
        [Display(Name = "Correo")]
        public string correo
        {
            get; set;
        }
        [Display(Name = "Provincia")]
        public string provincia
        {
            get; set;
        }
        [Display(Name = "Cantón")]
        public string canton
        {
            get; set;
        }
        [Display(Name = "Distrito")]
        public string distrito
        {
            get; set;
        }
        [Display(Name = "Dirección Exacta")]
        public string direccionExacta
        {
            get; set;
        }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto> Proyectoes { get; set; }
    }
}
