//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public int codigoPK { get; set; }
        public string nombre { get; set; }
        public int cantonFK { get; set; }
        public int provinciaFK { get; set; }
    
        public virtual Canton Canton { get; set; }
    }
}
