//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilidade
    {
        public string cedula_empleadoFK { get; set; }
        public string categoriaPK { get; set; }
        public string descripcionPK { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
