//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prueba
    {
        public int idPK { get; set; }
        public int id_proyectoFK { get; set; }
        public int id_requerimientoFK { get; set; }
        public string proposito { get; set; }
        public string entradaDatos { get; set; }
        public string flujo { get; set; }
        public string resultadoFinal { get; set; }
        public string resultadoEsperado { get; set; }
        public byte[] imgError { get; set; }
        public string descError { get; set; }
    
        public virtual Requerimiento Requerimiento { get; set; }
    }
}
