//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage" , "CA2214:DoNotCallOverridableMethodsInConstructors" )]
        public Requerimiento()
        {
            this.Pruebas = new HashSet<Prueba>( );
            this.TieneAsignadoes = new HashSet<TieneAsignado>( );
        }

        public int idPK
        {
            get; set;
        }
        [Display( Name = "Nombre" )]
        public string nombre
        {
            get; set;
        }
        public int id_proyectoFK
        {
            get; set;
        }
        [Display( Name = "Fecha de Inicio" )]
        public System.DateTime fechaInicio
        {
            get; set;
        }
        [Display( Name = "Fecha de Finalización" )]
        public Nullable<System.DateTime> fechaFinalizacion
        {
            get; set;
        }
        [Display( Name = "Fecha de Asignación" )]
        public Nullable<System.DateTime> fechaAsignacion
        {
            get; set;
        }
        [Display( Name = "Estado" )]
        public string estado
        {
            get; set;
        }
        [Display( Name = "Complejidad" )]
        public string complejidad
        {
            get; set;
        }
        [Display( Name = "Descripción" )]
        public string descripcion
        {
            get; set;
        }
        [Display( Name = "Duración Estimada" )]
        public float duracionEstimada
        {
            get; set;
        }
        [Display( Name = "Duración Real" )]
        public Nullable<float> duracionReal
        {
            get; set;
        }

        public virtual Proyecto Proyecto
        {
            get; set;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage" , "CA2227:CollectionPropertiesShouldBeReadOnly" )]
        public virtual ICollection<Prueba> Pruebas
        {
            get; set;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage( "Microsoft.Usage" , "CA2227:CollectionPropertiesShouldBeReadOnly" )]
        public virtual ICollection<TieneAsignado> TieneAsignadoes
        {
            get; set;
        }
    }
}
