//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieneAsignado
    {
        public string cedula_empleadoFK { get; set; }
        public int id_requerimientoFK { get; set; }
        public int id_proyectoFK { get; set; }
        public Nullable<float> horasDedicas { get; set; }
    
        public virtual Requerimiento Requerimiento { get; set; }
        public virtual Tester Tester { get; set; }
    }
}
